// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *C7NHelmRelease) DeepCopyInto(out *C7NHelmRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new C7NHelmRelease.
func (in *C7NHelmRelease) DeepCopy() *C7NHelmRelease {
	if in == nil {
		return nil
	}
	out := new(C7NHelmRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *C7NHelmRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *C7NHelmReleaseList) DeepCopyInto(out *C7NHelmReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]C7NHelmRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new C7NHelmReleaseList.
func (in *C7NHelmReleaseList) DeepCopy() *C7NHelmReleaseList {
	if in == nil {
		return nil
	}
	out := new(C7NHelmReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *C7NHelmReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *C7NHelmReleaseSpec) DeepCopyInto(out *C7NHelmReleaseSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new C7NHelmReleaseSpec.
func (in *C7NHelmReleaseSpec) DeepCopy() *C7NHelmReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(C7NHelmReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *C7NHelmReleaseStatus) DeepCopyInto(out *C7NHelmReleaseStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new C7NHelmReleaseStatus.
func (in *C7NHelmReleaseStatus) DeepCopy() *C7NHelmReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(C7NHelmReleaseStatus)
	in.DeepCopyInto(out)
	return out
}
