// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/choerodon/choerodon-cluster-agen1/pkg/apis/choerodon/v1alpha1.C7NHelmRelease":       schema_pkg_apis_choerodon_v1alpha1_C7NHelmRelease(ref),
		"github.com/choerodon/choerodon-cluster-agen1/pkg/apis/choerodon/v1alpha1.C7NHelmReleaseSpec":   schema_pkg_apis_choerodon_v1alpha1_C7NHelmReleaseSpec(ref),
		"github.com/choerodon/choerodon-cluster-agen1/pkg/apis/choerodon/v1alpha1.C7NHelmReleaseStatus": schema_pkg_apis_choerodon_v1alpha1_C7NHelmReleaseStatus(ref),
	}
}

func schema_pkg_apis_choerodon_v1alpha1_C7NHelmRelease(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "C7NHelmRelease is the Schema for the c7nhelmreleases API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/choerodon/choerodon-cluster-agen1/pkg/apis/choerodon/v1alpha1.C7NHelmReleaseSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/choerodon/choerodon-cluster-agen1/pkg/apis/choerodon/v1alpha1.C7NHelmReleaseStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/choerodon/choerodon-cluster-agen1/pkg/apis/choerodon/v1alpha1.C7NHelmReleaseSpec", "github.com/choerodon/choerodon-cluster-agen1/pkg/apis/choerodon/v1alpha1.C7NHelmReleaseStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_choerodon_v1alpha1_C7NHelmReleaseSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "C7NHelmReleaseSpec defines the desired state of C7NHelmRelease",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_choerodon_v1alpha1_C7NHelmReleaseStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "C7NHelmReleaseStatus defines the observed state of C7NHelmRelease",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
