// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/choerodon/choerodon-cluster-agent/pkg/apis/choerodon/v1alpha1"
	"github.com/choerodon/choerodon-cluster-agent/pkg/client/clientset/versioned/scheme"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
)

type ChoerodonV1alpha1Interface interface {
	RESTClient() rest.Interface
	C7NHelmReleasesGetter
}

// ChoerodonV1alpha1Client is used to interact with features provided by the choerodon.io group.
type ChoerodonV1alpha1Client struct {
	restClient rest.Interface
}

func (c *ChoerodonV1alpha1Client) C7NHelmReleases(namespace string) C7NHelmReleaseInterface {
	return newC7NHelmReleases(c, namespace)
}

// NewForConfig creates a new ChoerodonV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*ChoerodonV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &ChoerodonV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new ChoerodonV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ChoerodonV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ChoerodonV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *ChoerodonV1alpha1Client {
	return &ChoerodonV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ChoerodonV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
