// Code generated by informer-gen. DO NOT EDIT.

// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	choerodonv1alpha1 "github.com/choerodon/choerodon-agent/pkg/apis/choerodon/v1alpha1"
	versioned "github.com/choerodon/choerodon-agent/pkg/client/clientset/versioned"
	internalinterfaces "github.com/choerodon/choerodon-agent/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/choerodon/choerodon-agent/pkg/client/listers/choerodon/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// C7NHelmReleaseInformer provides access to a shared informer and lister for
// C7NHelmReleases.
type C7NHelmReleaseInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.C7NHelmReleaseLister
}

type c7NHelmReleaseInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewC7NHelmReleaseInformer constructs a new informer for C7NHelmRelease type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewC7NHelmReleaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredC7NHelmReleaseInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredC7NHelmReleaseInformer constructs a new informer for C7NHelmRelease type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredC7NHelmReleaseInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ChoerodonV1alpha1().C7NHelmReleases(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ChoerodonV1alpha1().C7NHelmReleases(namespace).Watch(options)
			},
		},
		&choerodonv1alpha1.C7NHelmRelease{},
		resyncPeriod,
		indexers,
	)
}

func (f *c7NHelmReleaseInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredC7NHelmReleaseInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *c7NHelmReleaseInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&choerodonv1alpha1.C7NHelmRelease{}, f.defaultInformer)
}

func (f *c7NHelmReleaseInformer) Lister() v1alpha1.C7NHelmReleaseLister {
	return v1alpha1.NewC7NHelmReleaseLister(f.Informer().GetIndexer())
}
