// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/choerodon/choerodon-cluster-agent/pkg/apis/choerodon/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeC7NHelmReleases implements C7NHelmReleaseInterface
type FakeC7NHelmReleases struct {
	Fake *FakeChoerodonV1alpha1
	ns   string
}

var c7nhelmreleasesResource = schema.GroupVersionResource{Group: "choerodon.io", Version: "v1alpha1", Resource: "c7nhelmreleases"}

var c7nhelmreleasesKind = schema.GroupVersionKind{Group: "choerodon.io", Version: "v1alpha1", Kind: "C7NHelmRelease"}

// Get takes name of the c7NHelmRelease, and returns the corresponding c7NHelmRelease object, and an error if there is any.
func (c *FakeC7NHelmReleases) Get(name string, options v1.GetOptions) (result *v1alpha1.C7NHelmRelease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(c7nhelmreleasesResource, c.ns, name), &v1alpha1.C7NHelmRelease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.C7NHelmRelease), err
}

// List takes label and field selectors, and returns the list of C7NHelmReleases that match those selectors.
func (c *FakeC7NHelmReleases) List(opts v1.ListOptions) (result *v1alpha1.C7NHelmReleaseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(c7nhelmreleasesResource, c7nhelmreleasesKind, c.ns, opts), &v1alpha1.C7NHelmReleaseList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.C7NHelmReleaseList{}
	for _, item := range obj.(*v1alpha1.C7NHelmReleaseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested c7NHelmReleases.
func (c *FakeC7NHelmReleases) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(c7nhelmreleasesResource, c.ns, opts))

}

// Create takes the representation of a c7NHelmRelease and creates it.  Returns the server's representation of the c7NHelmRelease, and an error, if there is any.
func (c *FakeC7NHelmReleases) Create(c7NHelmRelease *v1alpha1.C7NHelmRelease) (result *v1alpha1.C7NHelmRelease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(c7nhelmreleasesResource, c.ns, c7NHelmRelease), &v1alpha1.C7NHelmRelease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.C7NHelmRelease), err
}

// Update takes the representation of a c7NHelmRelease and updates it. Returns the server's representation of the c7NHelmRelease, and an error, if there is any.
func (c *FakeC7NHelmReleases) Update(c7NHelmRelease *v1alpha1.C7NHelmRelease) (result *v1alpha1.C7NHelmRelease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(c7nhelmreleasesResource, c.ns, c7NHelmRelease), &v1alpha1.C7NHelmRelease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.C7NHelmRelease), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeC7NHelmReleases) UpdateStatus(c7NHelmRelease *v1alpha1.C7NHelmRelease) (*v1alpha1.C7NHelmRelease, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(c7nhelmreleasesResource, "status", c.ns, c7NHelmRelease), &v1alpha1.C7NHelmRelease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.C7NHelmRelease), err
}

// Delete takes name of the c7NHelmRelease and deletes it. Returns an error if one occurs.
func (c *FakeC7NHelmReleases) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(c7nhelmreleasesResource, c.ns, name), &v1alpha1.C7NHelmRelease{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeC7NHelmReleases) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(c7nhelmreleasesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.C7NHelmReleaseList{})
	return err
}

// Patch applies the patch and returns the patched c7NHelmRelease.
func (c *FakeC7NHelmReleases) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.C7NHelmRelease, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(c7nhelmreleasesResource, c.ns, name, data, subresources...), &v1alpha1.C7NHelmRelease{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.C7NHelmRelease), err
}
