// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/choerodon/choerodon-cluster-agent/pkg/client/clientset/versioned/typed/choerodon/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeChoerodonV1alpha1 struct {
	*testing.Fake
}

func (c *FakeChoerodonV1alpha1) C7NHelmReleases(namespace string) v1alpha1.C7NHelmReleaseInterface {
	return &FakeC7NHelmReleases{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeChoerodonV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
