// Code generated by lister-gen. DO NOT EDIT.

// This file was automatically generated by lister-gen

package v1alpha1

import (
	v1alpha1 "github.com/choerodon/choerodon-cluster-agent/pkg/apis/choerodon/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// C7NHelmReleaseLister helps list C7NHelmReleases.
type C7NHelmReleaseLister interface {
	// List lists all C7NHelmReleases in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.C7NHelmRelease, err error)
	// C7NHelmReleases returns an object that can list and get C7NHelmReleases.
	C7NHelmReleases(namespace string) C7NHelmReleaseNamespaceLister
	C7NHelmReleaseListerExpansion
}

// c7NHelmReleaseLister implements the C7NHelmReleaseLister interface.
type c7NHelmReleaseLister struct {
	indexer cache.Indexer
}

// NewC7NHelmReleaseLister returns a new C7NHelmReleaseLister.
func NewC7NHelmReleaseLister(indexer cache.Indexer) C7NHelmReleaseLister {
	return &c7NHelmReleaseLister{indexer: indexer}
}

// List lists all C7NHelmReleases in the indexer.
func (s *c7NHelmReleaseLister) List(selector labels.Selector) (ret []*v1alpha1.C7NHelmRelease, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.C7NHelmRelease))
	})
	return ret, err
}

// C7NHelmReleases returns an object that can list and get C7NHelmReleases.
func (s *c7NHelmReleaseLister) C7NHelmReleases(namespace string) C7NHelmReleaseNamespaceLister {
	return c7NHelmReleaseNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// C7NHelmReleaseNamespaceLister helps list and get C7NHelmReleases.
type C7NHelmReleaseNamespaceLister interface {
	// List lists all C7NHelmReleases in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.C7NHelmRelease, err error)
	// Get retrieves the C7NHelmRelease from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.C7NHelmRelease, error)
	C7NHelmReleaseNamespaceListerExpansion
}

// c7NHelmReleaseNamespaceLister implements the C7NHelmReleaseNamespaceLister
// interface.
type c7NHelmReleaseNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all C7NHelmReleases in the indexer for a given namespace.
func (s c7NHelmReleaseNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.C7NHelmRelease, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.C7NHelmRelease))
	})
	return ret, err
}

// Get retrieves the C7NHelmRelease from the indexer for a given namespace and name.
func (s c7NHelmReleaseNamespaceLister) Get(name string) (*v1alpha1.C7NHelmRelease, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("c7nhelmrelease"), name)
	}
	return obj.(*v1alpha1.C7NHelmRelease), nil
}
