// Code generated by lister-gen. DO NOT EDIT.

// This file was automatically generated by lister-gen

package v1alpha1

// C7NHelmReleaseListerExpansion allows custom methods to be added to
// C7NHelmReleaseLister.
type C7NHelmReleaseListerExpansion interface{}

// C7NHelmReleaseNamespaceListerExpansion allows custom methods to be added to
// C7NHelmReleaseNamespaceLister.
type C7NHelmReleaseNamespaceListerExpansion interface{}
